language: cpp
compiler: gcc
branches:
  only:
    - master
before_install:
  - chmod a+x tool/setup-ubuntu.sh
install:
  - ./tool/setup-ubuntu.sh
  - cmake --version
  - g++ --version
before_script:
  - cd build
  - cmake ../project/
script:
  - cmake --build .
  - modurale/modurale-test
